
import java.util.*;

public class Test16 {

    public static void main(String[] args) {

        Tretja.Dogodek[] dogodki = {
            new Tretja.Rekreacija(4, new Cas(0, 10), true),
            new Tretja.Malica(13, new Cas(0, 24), true),
            new Tretja.Rekreacija(3, new Cas(0, 42), true),
            new Tretja.SluzbenaPot(14, new Cas(0, 48), true),
            new Tretja.Malica(6, new Cas(0, 51), true),
            new Tretja.Malica(1, new Cas(1, 15), true),
            new Tretja.Rekreacija(10, new Cas(1, 29), true),
            new Tretja.Rekreacija(2, new Cas(1, 38), true),
            new Tretja.Rekreacija(8, new Cas(1, 50), true),
            new Tretja.SluzbenaPot(11, new Cas(2, 37), true),
            new Tretja.Malica(1, new Cas(2, 47), false),
            new Tretja.Rekreacija(12, new Cas(2, 54), true),
            new Tretja.SluzbenaPot(9, new Cas(3, 27), true),
            new Tretja.Rekreacija(0, new Cas(3, 34), true),
            new Tretja.Malica(13, new Cas(3, 38), false),
            new Tretja.Malica(16, new Cas(3, 50), true),
            new Tretja.SluzbenaPot(7, new Cas(4, 23), true),
            new Tretja.Rekreacija(4, new Cas(4, 34), false),
            new Tretja.Rekreacija(0, new Cas(4, 46), false),
            new Tretja.SluzbenaPot(4, new Cas(4, 58), true),
            new Tretja.SluzbenaPot(4, new Cas(5, 48), false),
            new Tretja.Rekreacija(15, new Cas(5, 56), true),
            new Tretja.SluzbenaPot(5, new Cas(6, 3), true),
            new Tretja.Rekreacija(3, new Cas(6, 31), false),
            new Tretja.Rekreacija(3, new Cas(6, 37), true),
            new Tretja.Rekreacija(1, new Cas(6, 40), true),
            new Tretja.SluzbenaPot(17, new Cas(6, 45), true),
            new Tretja.Malica(4, new Cas(6, 46), true),
            new Tretja.SluzbenaPot(7, new Cas(7, 17), false),
            new Tretja.Rekreacija(0, new Cas(7, 30), true),
            new Tretja.SluzbenaPot(13, new Cas(7, 31), true),
            new Tretja.Rekreacija(12, new Cas(7, 37), false),
            new Tretja.Rekreacija(10, new Cas(7, 41), false),
            new Tretja.Rekreacija(2, new Cas(7, 59), false),
            new Tretja.SluzbenaPot(11, new Cas(8, 5), false),
            new Tretja.Rekreacija(10, new Cas(8, 21), true),
            new Tretja.SluzbenaPot(2, new Cas(8, 25), true),
            new Tretja.Rekreacija(15, new Cas(8, 32), false),
            new Tretja.SluzbenaPot(9, new Cas(8, 32), false),
            new Tretja.Rekreacija(7, new Cas(9, 3), true),
            new Tretja.SluzbenaPot(12, new Cas(9, 41), true),
            new Tretja.Rekreacija(8, new Cas(9, 41), false),
            new Tretja.SluzbenaPot(14, new Cas(10, 4), false),
            new Tretja.Rekreacija(7, new Cas(10, 21), false),
            new Tretja.SluzbenaPot(11, new Cas(11, 20), true),
            new Tretja.Rekreacija(14, new Cas(11, 21), true),
            new Tretja.Rekreacija(8, new Cas(11, 25), true),
            new Tretja.Rekreacija(10, new Cas(12, 5), false),
            new Tretja.Rekreacija(3, new Cas(12, 19), false),
            new Tretja.SluzbenaPot(5, new Cas(12, 27), false),
            new Tretja.Malica(15, new Cas(12, 31), true),
            new Tretja.Rekreacija(7, new Cas(12, 41), true),
            new Tretja.Malica(4, new Cas(12, 57), false),
            new Tretja.Rekreacija(8, new Cas(13, 11), false),
            new Tretja.Rekreacija(7, new Cas(14, 10), false),
            new Tretja.Rekreacija(5, new Cas(14, 42), true),
            new Tretja.Malica(10, new Cas(14, 59), true),
            new Tretja.Rekreacija(4, new Cas(15, 21), true),
            new Tretja.Rekreacija(3, new Cas(15, 41), true),
            new Tretja.Rekreacija(9, new Cas(15, 45), true),
            new Tretja.SluzbenaPot(11, new Cas(15, 48), false),
            new Tretja.Rekreacija(5, new Cas(16, 19), false),
            new Tretja.Rekreacija(1, new Cas(16, 41), false),
            new Tretja.SluzbenaPot(2, new Cas(16, 43), false),
            new Tretja.Malica(8, new Cas(16, 56), true),
            new Tretja.Rekreacija(7, new Cas(16, 56), true),
            new Tretja.Malica(6, new Cas(17, 4), false),
            new Tretja.Rekreacija(4, new Cas(17, 10), false),
            new Tretja.Malica(16, new Cas(17, 21), false),
            new Tretja.Malica(5, new Cas(17, 50), true),
            new Tretja.Rekreacija(14, new Cas(18, 0), false),
            new Tretja.Malica(5, new Cas(18, 23), false),
            new Tretja.Rekreacija(3, new Cas(18, 59), false),
            new Tretja.Malica(10, new Cas(19, 36), false),
            new Tretja.Rekreacija(9, new Cas(19, 38), false),
            new Tretja.Malica(15, new Cas(19, 41), false),
            new Tretja.SluzbenaPot(3, new Cas(19, 43), true),
            new Tretja.Rekreacija(15, new Cas(19, 44), true),
            new Tretja.SluzbenaPot(3, new Cas(20, 26), false),
            new Tretja.SluzbenaPot(17, new Cas(20, 28), false),
            new Tretja.SluzbenaPot(12, new Cas(20, 39), false),
            new Tretja.Rekreacija(0, new Cas(20, 41), false),
            new Tretja.Rekreacija(11, new Cas(20, 46), true),
            new Tretja.Rekreacija(15, new Cas(21, 6), false),
            new Tretja.Malica(8, new Cas(21, 27), false),
            new Tretja.SluzbenaPot(5, new Cas(22, 24), true),
            new Tretja.Rekreacija(7, new Cas(22, 37), false),
            new Tretja.SluzbenaPot(5, new Cas(22, 44), false),
            new Tretja.Rekreacija(11, new Cas(22, 58), false),
            new Tretja.Rekreacija(5, new Cas(22, 59), true),
            new Tretja.SluzbenaPot(13, new Cas(23, 25), false),
            new Tretja.Rekreacija(5, new Cas(23, 58), false),
        };

        int stZaposlenih = 18;
        Tretja.Dnevnik dnevnik = new Tretja.Dnevnik(stZaposlenih, dogodki);

        System.out.println(dnevnik.steviloMalicarjev());
        System.out.println();
    }
}
