
import java.util.*;

public class Test36 {

    public static void main(String[] args) {

        Tretja.Dogodek[] dogodki = {
            new Tretja.SluzbenaPot(7, new Cas(0, 6), true),
            new Tretja.Rekreacija(8, new Cas(0, 7), true),
            new Tretja.Rekreacija(2, new Cas(0, 10), true),
            new Tretja.Rekreacija(46, new Cas(0, 12), true),
            new Tretja.SluzbenaPot(19, new Cas(0, 15), true),
            new Tretja.Malica(0, new Cas(0, 21), true),
            new Tretja.SluzbenaPot(5, new Cas(0, 23), true),
            new Tretja.Rekreacija(2, new Cas(0, 27), false),
            new Tretja.Rekreacija(18, new Cas(0, 30), true),
            new Tretja.Rekreacija(16, new Cas(0, 33), true),
            new Tretja.SluzbenaPot(48, new Cas(0, 34), true),
            new Tretja.Rekreacija(44, new Cas(0, 52), true),
            new Tretja.Malica(22, new Cas(1, 9), true),
            new Tretja.Malica(40, new Cas(1, 17), true),
            new Tretja.SluzbenaPot(39, new Cas(1, 23), true),
            new Tretja.SluzbenaPot(6, new Cas(1, 27), true),
            new Tretja.SluzbenaPot(15, new Cas(1, 27), true),
            new Tretja.Malica(10, new Cas(1, 29), true),
            new Tretja.Rekreacija(3, new Cas(1, 30), true),
            new Tretja.SluzbenaPot(35, new Cas(1, 37), true),
            new Tretja.Malica(26, new Cas(1, 44), true),
            new Tretja.SluzbenaPot(29, new Cas(1, 45), true),
            new Tretja.Rekreacija(47, new Cas(1, 47), true),
            new Tretja.Malica(30, new Cas(1, 48), true),
            new Tretja.Malica(4, new Cas(1, 53), true),
            new Tretja.Rekreacija(46, new Cas(1, 55), false),
            new Tretja.SluzbenaPot(19, new Cas(1, 57), false),
            new Tretja.Rekreacija(37, new Cas(1, 57), true),
            new Tretja.Rekreacija(38, new Cas(2, 9), true),
            new Tretja.SluzbenaPot(1, new Cas(2, 11), true),
            new Tretja.Malica(45, new Cas(2, 15), true),
            new Tretja.Rekreacija(41, new Cas(2, 28), true),
            new Tretja.Rekreacija(32, new Cas(2, 38), true),
            new Tretja.SluzbenaPot(28, new Cas(2, 39), true),
            new Tretja.Rekreacija(38, new Cas(3, 2), false),
            new Tretja.Malica(20, new Cas(3, 3), true),
            new Tretja.Rekreacija(3, new Cas(3, 12), false),
            new Tretja.Rekreacija(19, new Cas(3, 12), true),
            new Tretja.Malica(13, new Cas(3, 23), true),
            new Tretja.SluzbenaPot(28, new Cas(3, 30), false),
            new Tretja.Rekreacija(37, new Cas(3, 32), false),
            new Tretja.Malica(12, new Cas(3, 35), true),
            new Tretja.SluzbenaPot(36, new Cas(3, 42), true),
            new Tretja.Rekreacija(34, new Cas(3, 43), true),
            new Tretja.Malica(40, new Cas(3, 43), false),
            new Tretja.Malica(46, new Cas(3, 46), true),
            new Tretja.Malica(2, new Cas(3, 47), true),
            new Tretja.Rekreacija(24, new Cas(3, 55), true),
            new Tretja.Rekreacija(38, new Cas(3, 55), true),
            new Tretja.Malica(31, new Cas(4, 5), true),
            new Tretja.Rekreacija(19, new Cas(4, 11), false),
            new Tretja.Malica(49, new Cas(4, 11), true),
            new Tretja.SluzbenaPot(25, new Cas(4, 15), true),
            new Tretja.Rekreacija(3, new Cas(4, 16), true),
            new Tretja.SluzbenaPot(19, new Cas(4, 16), true),
            new Tretja.Rekreacija(42, new Cas(4, 21), true),
            new Tretja.Rekreacija(42, new Cas(4, 23), false),
            new Tretja.Malica(12, new Cas(4, 28), false),
            new Tretja.Rekreacija(33, new Cas(4, 31), true),
            new Tretja.SluzbenaPot(12, new Cas(4, 31), true),
            new Tretja.Rekreacija(32, new Cas(4, 32), false),
            new Tretja.SluzbenaPot(11, new Cas(4, 33), true),
            new Tretja.Rekreacija(28, new Cas(4, 34), true),
            new Tretja.SluzbenaPot(36, new Cas(4, 34), false),
            new Tretja.SluzbenaPot(39, new Cas(4, 35), false),
            new Tretja.Malica(36, new Cas(4, 36), true),
            new Tretja.Malica(9, new Cas(4, 39), true),
            new Tretja.SluzbenaPot(27, new Cas(4, 47), true),
            new Tretja.Malica(0, new Cas(4, 49), false),
            new Tretja.Rekreacija(17, new Cas(4, 54), true),
            new Tretja.SluzbenaPot(35, new Cas(5, 1), false),
            new Tretja.Rekreacija(32, new Cas(5, 6), true),
            new Tretja.SluzbenaPot(21, new Cas(5, 9), true),
            new Tretja.SluzbenaPot(43, new Cas(5, 17), true),
            new Tretja.Rekreacija(23, new Cas(5, 23), true),
            new Tretja.Rekreacija(14, new Cas(5, 25), true),
            new Tretja.Malica(42, new Cas(5, 32), true),
            new Tretja.Rekreacija(40, new Cas(5, 36), true),
            new Tretja.SluzbenaPot(6, new Cas(5, 38), false),
            new Tretja.SluzbenaPot(37, new Cas(5, 42), true),
            new Tretja.Rekreacija(41, new Cas(5, 53), false),
            new Tretja.SluzbenaPot(35, new Cas(5, 58), true),
            new Tretja.Rekreacija(18, new Cas(6, 2), false),
            new Tretja.Rekreacija(6, new Cas(6, 3), true),
            new Tretja.SluzbenaPot(0, new Cas(6, 6), true),
            new Tretja.SluzbenaPot(19, new Cas(6, 6), false),
            new Tretja.SluzbenaPot(41, new Cas(6, 8), true),
            new Tretja.SluzbenaPot(18, new Cas(6, 11), true),
            new Tretja.Rekreacija(16, new Cas(6, 14), false),
            new Tretja.Rekreacija(32, new Cas(6, 21), false),
            new Tretja.SluzbenaPot(32, new Cas(6, 39), true),
            new Tretja.Malica(39, new Cas(6, 42), true),
            new Tretja.SluzbenaPot(21, new Cas(6, 53), false),
            new Tretja.Malica(13, new Cas(6, 56), false),
            new Tretja.SluzbenaPot(43, new Cas(6, 58), false),
            new Tretja.Malica(10, new Cas(6, 58), false),
            new Tretja.SluzbenaPot(18, new Cas(7, 0), false),
            new Tretja.SluzbenaPot(5, new Cas(7, 8), false),
            new Tretja.Rekreacija(3, new Cas(7, 11), false),
            new Tretja.Rekreacija(17, new Cas(7, 15), false),
            new Tretja.Rekreacija(14, new Cas(7, 17), false),
            new Tretja.Malica(43, new Cas(7, 17), true),
            new Tretja.Rekreacija(6, new Cas(7, 18), false),
            new Tretja.Rekreacija(13, new Cas(7, 20), true),
            new Tretja.Malica(20, new Cas(7, 21), false),
            new Tretja.SluzbenaPot(10, new Cas(7, 24), true),
            new Tretja.Malica(5, new Cas(7, 29), true),
            new Tretja.Malica(16, new Cas(7, 33), true),
            new Tretja.SluzbenaPot(20, new Cas(7, 53), true),
            new Tretja.Malica(18, new Cas(7, 57), true),
            new Tretja.Rekreacija(23, new Cas(8, 4), false),
            new Tretja.Rekreacija(34, new Cas(8, 11), false),
            new Tretja.Malica(9, new Cas(8, 12), false),
            new Tretja.Rekreacija(34, new Cas(8, 19), true),
            new Tretja.Rekreacija(19, new Cas(8, 22), true),
            new Tretja.SluzbenaPot(32, new Cas(8, 23), false),
            new Tretja.Rekreacija(6, new Cas(8, 28), true),
            new Tretja.Rekreacija(14, new Cas(8, 42), true),
            new Tretja.SluzbenaPot(32, new Cas(8, 46), true),
            new Tretja.SluzbenaPot(10, new Cas(8, 52), false),
            new Tretja.SluzbenaPot(48, new Cas(8, 53), false),
            new Tretja.SluzbenaPot(3, new Cas(8, 55), true),
            new Tretja.Rekreacija(14, new Cas(8, 58), false),
            new Tretja.SluzbenaPot(14, new Cas(9, 12), true),
            new Tretja.Rekreacija(28, new Cas(9, 14), false),
            new Tretja.SluzbenaPot(48, new Cas(9, 18), true),
            new Tretja.Rekreacija(34, new Cas(9, 23), false),
            new Tretja.SluzbenaPot(23, new Cas(9, 26), true),
            new Tretja.Rekreacija(9, new Cas(9, 31), true),
            new Tretja.SluzbenaPot(28, new Cas(9, 35), true),
            new Tretja.Malica(18, new Cas(9, 41), false),
            new Tretja.Rekreacija(10, new Cas(9, 47), true),
            new Tretja.Rekreacija(13, new Cas(9, 49), false),
            new Tretja.SluzbenaPot(41, new Cas(9, 53), false),
            new Tretja.SluzbenaPot(23, new Cas(9, 54), false),
            new Tretja.Rekreacija(21, new Cas(9, 54), true),
            new Tretja.SluzbenaPot(18, new Cas(10, 2), true),
            new Tretja.SluzbenaPot(25, new Cas(10, 14), false),
            new Tretja.SluzbenaPot(1, new Cas(10, 15), false),
            new Tretja.SluzbenaPot(23, new Cas(10, 17), true),
            new Tretja.Malica(34, new Cas(10, 24), true),
            new Tretja.Rekreacija(47, new Cas(10, 26), false),
            new Tretja.Rekreacija(33, new Cas(10, 30), false),
            new Tretja.SluzbenaPot(1, new Cas(10, 31), true),
            new Tretja.Malica(25, new Cas(10, 33), true),
            new Tretja.SluzbenaPot(0, new Cas(10, 42), false),
            new Tretja.Rekreacija(41, new Cas(10, 47), true),
            new Tretja.Malica(17, new Cas(10, 48), true),
            new Tretja.Rekreacija(0, new Cas(10, 52), true),
            new Tretja.SluzbenaPot(13, new Cas(11, 1), true),
            new Tretja.Rekreacija(6, new Cas(11, 3), false),
            new Tretja.SluzbenaPot(33, new Cas(11, 5), true),
            new Tretja.SluzbenaPot(6, new Cas(11, 11), true),
            new Tretja.SluzbenaPot(32, new Cas(11, 12), false),
            new Tretja.SluzbenaPot(6, new Cas(11, 17), false),
            new Tretja.Rekreacija(10, new Cas(11, 19), false),
            new Tretja.Rekreacija(8, new Cas(11, 26), false),
            new Tretja.Rekreacija(47, new Cas(11, 28), true),
            new Tretja.Rekreacija(10, new Cas(11, 32), true),
            new Tretja.SluzbenaPot(1, new Cas(11, 33), false),
            new Tretja.Rekreacija(0, new Cas(11, 37), false),
            new Tretja.Rekreacija(8, new Cas(11, 39), true),
            new Tretja.SluzbenaPot(32, new Cas(11, 46), true),
            new Tretja.Malica(39, new Cas(11, 51), false),
            new Tretja.Malica(6, new Cas(11, 55), true),
            new Tretja.Rekreacija(0, new Cas(11, 56), true),
            new Tretja.SluzbenaPot(3, new Cas(12, 1), false),
            new Tretja.Malica(1, new Cas(12, 2), true),
            new Tretja.Rekreacija(10, new Cas(12, 14), false),
            new Tretja.SluzbenaPot(20, new Cas(12, 14), false),
            new Tretja.Rekreacija(39, new Cas(12, 15), true),
            new Tretja.SluzbenaPot(3, new Cas(12, 19), true),
            new Tretja.Rekreacija(20, new Cas(12, 22), true),
            new Tretja.Rekreacija(47, new Cas(12, 24), false),
            new Tretja.Rekreacija(21, new Cas(12, 26), false),
            new Tretja.SluzbenaPot(7, new Cas(12, 40), false),
            new Tretja.Malica(47, new Cas(12, 50), true),
            new Tretja.Rekreacija(10, new Cas(13, 7), true),
            new Tretja.SluzbenaPot(33, new Cas(13, 8), false),
            new Tretja.Rekreacija(21, new Cas(13, 16), true),
            new Tretja.Rekreacija(19, new Cas(13, 18), false),
            new Tretja.Rekreacija(21, new Cas(13, 19), false),
            new Tretja.SluzbenaPot(23, new Cas(13, 21), false),
            new Tretja.Rekreacija(8, new Cas(13, 30), false),
            new Tretja.Rekreacija(10, new Cas(13, 32), false),
            new Tretja.SluzbenaPot(29, new Cas(13, 36), false),
            new Tretja.Rekreacija(39, new Cas(13, 42), false),
            new Tretja.SluzbenaPot(15, new Cas(13, 44), false),
            new Tretja.SluzbenaPot(3, new Cas(13, 45), false),
            new Tretja.SluzbenaPot(18, new Cas(13, 47), false),
            new Tretja.SluzbenaPot(7, new Cas(13, 48), true),
            new Tretja.Malica(33, new Cas(13, 48), true),
            new Tretja.Rekreacija(10, new Cas(13, 49), true),
            new Tretja.Malica(23, new Cas(13, 50), true),
            new Tretja.Rekreacija(18, new Cas(13, 53), true),
            new Tretja.Malica(15, new Cas(13, 53), true),
            new Tretja.Malica(2, new Cas(13, 57), false),
            new Tretja.Malica(36, new Cas(13, 58), false),
            new Tretja.Malica(21, new Cas(14, 1), true),
            new Tretja.SluzbenaPot(13, new Cas(14, 6), false),
            new Tretja.Malica(19, new Cas(14, 6), true),
            new Tretja.Rekreacija(39, new Cas(14, 8), true),
            new Tretja.Malica(33, new Cas(14, 9), false),
            new Tretja.Malica(31, new Cas(14, 10), false),
            new Tretja.Rekreacija(3, new Cas(14, 11), true),
            new Tretja.Rekreacija(31, new Cas(14, 12), true),
            new Tretja.SluzbenaPot(28, new Cas(14, 18), false),
            new Tretja.Rekreacija(18, new Cas(14, 20), false),
            new Tretja.Malica(1, new Cas(14, 26), false),
            new Tretja.Rekreacija(29, new Cas(14, 27), true),
            new Tretja.SluzbenaPot(8, new Cas(14, 37), true),
            new Tretja.Rekreacija(33, new Cas(14, 42), true),
            new Tretja.SluzbenaPot(18, new Cas(14, 45), true),
            new Tretja.Malica(23, new Cas(14, 47), false),
            new Tretja.SluzbenaPot(1, new Cas(14, 48), true),
            new Tretja.Malica(16, new Cas(15, 3), false),
            new Tretja.SluzbenaPot(23, new Cas(15, 15), true),
            new Tretja.Malica(25, new Cas(15, 19), false),
            new Tretja.SluzbenaPot(8, new Cas(15, 20), false),
            new Tretja.Malica(22, new Cas(15, 22), false),
            new Tretja.SluzbenaPot(1, new Cas(15, 28), false),
            new Tretja.Malica(19, new Cas(15, 34), false),
            new Tretja.Rekreacija(1, new Cas(15, 36), true),
            new Tretja.SluzbenaPot(22, new Cas(15, 39), true),
            new Tretja.Rekreacija(16, new Cas(15, 51), true),
            new Tretja.Rekreacija(2, new Cas(15, 52), true),
            new Tretja.Rekreacija(33, new Cas(15, 56), false),
            new Tretja.Malica(49, new Cas(15, 58), false),
            new Tretja.Malica(34, new Cas(15, 58), false),
            new Tretja.SluzbenaPot(13, new Cas(16, 0), true),
            new Tretja.SluzbenaPot(14, new Cas(16, 2), false),
            new Tretja.Rekreacija(2, new Cas(16, 9), false),
            new Tretja.Rekreacija(24, new Cas(16, 11), false),
            new Tretja.Rekreacija(33, new Cas(16, 21), true),
            new Tretja.Malica(8, new Cas(16, 29), true),
            new Tretja.Malica(6, new Cas(16, 31), false),
            new Tretja.SluzbenaPot(25, new Cas(16, 32), true),
            new Tretja.SluzbenaPot(19, new Cas(16, 35), true),
            new Tretja.Rekreacija(49, new Cas(16, 37), true),
            new Tretja.Malica(47, new Cas(16, 53), false),
            new Tretja.Rekreacija(3, new Cas(16, 59), false),
            new Tretja.Rekreacija(6, new Cas(17, 0), true),
            new Tretja.Rekreacija(14, new Cas(17, 5), true),
            new Tretja.Rekreacija(29, new Cas(17, 6), false),
            new Tretja.Rekreacija(2, new Cas(17, 11), true),
            new Tretja.Rekreacija(44, new Cas(17, 18), false),
            new Tretja.Malica(4, new Cas(17, 22), false),
            new Tretja.Rekreacija(4, new Cas(17, 24), true),
            new Tretja.SluzbenaPot(22, new Cas(17, 27), false),
            new Tretja.Rekreacija(49, new Cas(17, 37), false),
            new Tretja.Rekreacija(29, new Cas(17, 39), true),
            new Tretja.Rekreacija(34, new Cas(17, 49), true),
            new Tretja.SluzbenaPot(11, new Cas(17, 58), false),
            new Tretja.Rekreacija(44, new Cas(18, 1), true),
            new Tretja.SluzbenaPot(36, new Cas(18, 5), true),
            new Tretja.Malica(28, new Cas(18, 9), true),
            new Tretja.Malica(3, new Cas(18, 17), true),
            new Tretja.Rekreacija(29, new Cas(18, 22), false),
            new Tretja.Malica(46, new Cas(18, 25), false),
            new Tretja.Malica(29, new Cas(18, 30), true),
            new Tretja.Malica(30, new Cas(18, 35), false),
            new Tretja.Malica(24, new Cas(18, 37), true),
            new Tretja.SluzbenaPot(35, new Cas(18, 39), false),
            new Tretja.SluzbenaPot(32, new Cas(18, 45), false),
            new Tretja.SluzbenaPot(47, new Cas(18, 47), true),
            new Tretja.Rekreacija(30, new Cas(18, 52), true),
            new Tretja.Malica(43, new Cas(19, 4), false),
            new Tretja.SluzbenaPot(49, new Cas(19, 7), true),
            new Tretja.Rekreacija(11, new Cas(19, 10), true),
            new Tretja.Rekreacija(9, new Cas(19, 11), false),
            new Tretja.SluzbenaPot(37, new Cas(19, 14), false),
            new Tretja.Rekreacija(4, new Cas(19, 14), false),
            new Tretja.Rekreacija(32, new Cas(19, 18), true),
            new Tretja.SluzbenaPot(43, new Cas(19, 24), true),
            new Tretja.Rekreacija(1, new Cas(19, 25), false),
            new Tretja.Rekreacija(46, new Cas(19, 36), true),
            new Tretja.SluzbenaPot(23, new Cas(19, 51), false),
            new Tretja.Rekreacija(22, new Cas(19, 54), true),
            new Tretja.Malica(28, new Cas(19, 57), false),
            new Tretja.Rekreacija(39, new Cas(19, 59), false),
            new Tretja.Rekreacija(16, new Cas(20, 2), false),
            new Tretja.Rekreacija(39, new Cas(20, 7), true),
            new Tretja.SluzbenaPot(36, new Cas(20, 8), false),
            new Tretja.Rekreacija(40, new Cas(20, 8), false),
            new Tretja.Malica(21, new Cas(20, 16), false),
            new Tretja.Rekreacija(41, new Cas(20, 16), false),
            new Tretja.SluzbenaPot(7, new Cas(20, 20), false),
            new Tretja.Rekreacija(33, new Cas(20, 25), false),
            new Tretja.SluzbenaPot(27, new Cas(20, 27), false),
            new Tretja.SluzbenaPot(13, new Cas(20, 27), false),
            new Tretja.SluzbenaPot(48, new Cas(20, 28), false),
            new Tretja.Rekreacija(22, new Cas(20, 30), false),
            new Tretja.SluzbenaPot(49, new Cas(20, 39), false),
            new Tretja.SluzbenaPot(48, new Cas(20, 39), true),
            new Tretja.Malica(17, new Cas(20, 50), false),
            new Tretja.Rekreacija(20, new Cas(20, 50), false),
            new Tretja.SluzbenaPot(12, new Cas(21, 2), false),
            new Tretja.Rekreacija(44, new Cas(21, 11), false),
            new Tretja.Malica(15, new Cas(21, 17), false),
            new Tretja.Rekreacija(0, new Cas(21, 18), false),
            new Tretja.Malica(26, new Cas(21, 19), false),
            new Tretja.SluzbenaPot(48, new Cas(21, 23), false),
            new Tretja.Rekreacija(33, new Cas(21, 27), true),
            new Tretja.Malica(24, new Cas(21, 29), false),
            new Tretja.Rekreacija(16, new Cas(21, 32), true),
            new Tretja.SluzbenaPot(47, new Cas(21, 35), false),
            new Tretja.Rekreacija(26, new Cas(21, 36), true),
            new Tretja.SluzbenaPot(19, new Cas(21, 45), false),
            new Tretja.Rekreacija(34, new Cas(21, 46), false),
            new Tretja.Rekreacija(30, new Cas(21, 46), false),
            new Tretja.Rekreacija(2, new Cas(21, 47), false),
            new Tretja.Malica(5, new Cas(21, 47), false),
            new Tretja.Rekreacija(38, new Cas(21, 52), false),
            new Tretja.SluzbenaPot(43, new Cas(21, 53), false),
            new Tretja.SluzbenaPot(25, new Cas(21, 55), false),
            new Tretja.Rekreacija(32, new Cas(21, 55), false),
            new Tretja.Rekreacija(21, new Cas(22, 6), true),
            new Tretja.SluzbenaPot(18, new Cas(22, 9), false),
            new Tretja.Rekreacija(10, new Cas(22, 10), false),
            new Tretja.Malica(8, new Cas(22, 32), false),
            new Tretja.Rekreacija(31, new Cas(22, 42), false),
            new Tretja.SluzbenaPot(43, new Cas(22, 46), true),
            new Tretja.Rekreacija(46, new Cas(22, 50), false),
            new Tretja.Malica(42, new Cas(23, 1), false),
            new Tretja.SluzbenaPot(43, new Cas(23, 1), false),
            new Tretja.Rekreacija(16, new Cas(23, 2), false),
            new Tretja.Rekreacija(26, new Cas(23, 3), false),
            new Tretja.Malica(29, new Cas(23, 18), false),
            new Tretja.Rekreacija(11, new Cas(23, 20), false),
            new Tretja.Malica(3, new Cas(23, 34), false),
            new Tretja.Rekreacija(6, new Cas(23, 35), false),
            new Tretja.Rekreacija(21, new Cas(23, 36), false),
            new Tretja.Rekreacija(33, new Cas(23, 38), false),
            new Tretja.Rekreacija(14, new Cas(23, 47), false),
            new Tretja.Malica(45, new Cas(23, 53), false),
            new Tretja.Rekreacija(39, new Cas(23, 57), false),
        };

        int stZaposlenih = 50;
        Tretja.Dnevnik dnevnik = new Tretja.Dnevnik(stZaposlenih, dogodki);

        List<Cas> casi = new ArrayList<>();
        casi.add(new Cas(0, 6));
        casi.add(new Cas(0, 43));
        casi.add(new Cas(1, 56));
        casi.add(new Cas(1, 58));
        casi.add(new Cas(2, 15));
        casi.add(new Cas(3, 32));
        casi.add(new Cas(3, 44));
        casi.add(new Cas(3, 55));
        casi.add(new Cas(4, 7));
        casi.add(new Cas(4, 37));
        casi.add(new Cas(4, 40));
        casi.add(new Cas(6, 33));
        casi.add(new Cas(7, 50));
        casi.add(new Cas(8, 20));
        casi.add(new Cas(9, 50));
        casi.add(new Cas(10, 45));
        casi.add(new Cas(10, 58));
        casi.add(new Cas(11, 4));
        casi.add(new Cas(11, 17));
        casi.add(new Cas(11, 51));
        casi.add(new Cas(12, 0));
        casi.add(new Cas(12, 16));
        casi.add(new Cas(13, 38));
        casi.add(new Cas(14, 26));
        casi.add(new Cas(14, 56));
        casi.add(new Cas(17, 20));
        casi.add(new Cas(21, 24));
        casi.add(new Cas(21, 30));
        casi.add(new Cas(21, 53));
        casi.add(new Cas(22, 49));

        for (Cas cas: casi) {
            System.out.printf("%s -> %s%n", cas, Arrays.toString(dnevnik.prisotnost(cas)));
        }
    }
}
