
import java.util.*;

public class Test32 {

    public static void main(String[] args) {

        Tretja.Dogodek[] dogodki = {
            new Tretja.Malica(21, new Cas(0, 13), true),
            new Tretja.SluzbenaPot(20, new Cas(0, 25), true),
            new Tretja.Rekreacija(6, new Cas(0, 55), true),
            new Tretja.Malica(17, new Cas(1, 25), true),
            new Tretja.Malica(8, new Cas(1, 37), true),
            new Tretja.Malica(22, new Cas(1, 54), true),
            new Tretja.Rekreacija(2, new Cas(1, 58), true),
            new Tretja.SluzbenaPot(9, new Cas(2, 30), true),
            new Tretja.SluzbenaPot(15, new Cas(2, 31), true),
            new Tretja.SluzbenaPot(1, new Cas(2, 32), true),
            new Tretja.Rekreacija(14, new Cas(3, 34), true),
            new Tretja.Rekreacija(23, new Cas(3, 45), true),
            new Tretja.SluzbenaPot(7, new Cas(4, 7), true),
            new Tretja.SluzbenaPot(9, new Cas(4, 40), false),
            new Tretja.Rekreacija(23, new Cas(4, 49), false),
            new Tretja.Malica(13, new Cas(4, 50), true),
            new Tretja.Malica(17, new Cas(4, 51), false),
            new Tretja.Rekreacija(14, new Cas(5, 8), false),
            new Tretja.SluzbenaPot(10, new Cas(5, 26), true),
            new Tretja.SluzbenaPot(3, new Cas(5, 32), true),
            new Tretja.SluzbenaPot(5, new Cas(6, 11), true),
            new Tretja.Malica(21, new Cas(6, 23), false),
            new Tretja.SluzbenaPot(17, new Cas(6, 42), true),
            new Tretja.Rekreacija(21, new Cas(6, 42), true),
            new Tretja.SluzbenaPot(4, new Cas(7, 13), true),
            new Tretja.SluzbenaPot(0, new Cas(7, 15), true),
            new Tretja.Rekreacija(2, new Cas(7, 24), false),
            new Tretja.SluzbenaPot(14, new Cas(7, 24), true),
            new Tretja.SluzbenaPot(3, new Cas(7, 28), false),
            new Tretja.Rekreacija(19, new Cas(7, 29), true),
            new Tretja.Malica(8, new Cas(7, 56), false),
            new Tretja.Rekreacija(12, new Cas(8, 9), true),
            new Tretja.Rekreacija(19, new Cas(8, 29), false),
            new Tretja.SluzbenaPot(16, new Cas(8, 39), true),
            new Tretja.Rekreacija(11, new Cas(8, 56), true),
            new Tretja.Malica(3, new Cas(9, 8), true),
            new Tretja.SluzbenaPot(18, new Cas(9, 13), true),
            new Tretja.Rekreacija(19, new Cas(9, 26), true),
            new Tretja.SluzbenaPot(16, new Cas(9, 49), false),
            new Tretja.Malica(16, new Cas(10, 11), true),
            new Tretja.Malica(2, new Cas(10, 40), true),
            new Tretja.Malica(13, new Cas(10, 45), false),
            new Tretja.Rekreacija(8, new Cas(10, 47), true),
            new Tretja.Rekreacija(6, new Cas(11, 3), false),
            new Tretja.Rekreacija(9, new Cas(11, 3), true),
            new Tretja.SluzbenaPot(1, new Cas(11, 4), false),
            new Tretja.SluzbenaPot(23, new Cas(11, 5), true),
            new Tretja.Rekreacija(13, new Cas(11, 12), true),
            new Tretja.SluzbenaPot(18, new Cas(11, 14), false),
            new Tretja.Malica(2, new Cas(11, 14), false),
            new Tretja.Rekreacija(19, new Cas(11, 20), false),
            new Tretja.Rekreacija(12, new Cas(11, 20), false),
            new Tretja.Rekreacija(1, new Cas(11, 21), true),
            new Tretja.Rekreacija(13, new Cas(11, 29), false),
            new Tretja.SluzbenaPot(20, new Cas(11, 42), false),
            new Tretja.Rekreacija(18, new Cas(11, 43), true),
            new Tretja.SluzbenaPot(20, new Cas(11, 51), true),
            new Tretja.Rekreacija(9, new Cas(11, 55), false),
            new Tretja.Rekreacija(13, new Cas(11, 56), true),
            new Tretja.Rekreacija(21, new Cas(11, 56), false),
            new Tretja.SluzbenaPot(9, new Cas(11, 57), true),
            new Tretja.SluzbenaPot(23, new Cas(12, 5), false),
            new Tretja.Rekreacija(2, new Cas(12, 13), true),
            new Tretja.SluzbenaPot(12, new Cas(12, 15), true),
            new Tretja.Malica(16, new Cas(12, 24), false),
            new Tretja.SluzbenaPot(21, new Cas(12, 33), true),
            new Tretja.SluzbenaPot(15, new Cas(12, 34), false),
            new Tretja.Rekreacija(19, new Cas(12, 37), true),
            new Tretja.Rekreacija(13, new Cas(12, 47), false),
            new Tretja.SluzbenaPot(21, new Cas(13, 6), false),
            new Tretja.SluzbenaPot(23, new Cas(13, 7), true),
            new Tretja.Rekreacija(21, new Cas(13, 22), true),
            new Tretja.Rekreacija(18, new Cas(13, 30), false),
            new Tretja.Rekreacija(6, new Cas(13, 42), true),
            new Tretja.Rekreacija(15, new Cas(13, 47), true),
            new Tretja.SluzbenaPot(12, new Cas(14, 8), false),
            new Tretja.SluzbenaPot(10, new Cas(14, 14), false),
            new Tretja.SluzbenaPot(0, new Cas(15, 4), false),
            new Tretja.SluzbenaPot(0, new Cas(15, 5), true),
            new Tretja.SluzbenaPot(10, new Cas(15, 33), true),
            new Tretja.Rekreacija(19, new Cas(16, 17), false),
            new Tretja.Rekreacija(16, new Cas(16, 38), true),
            new Tretja.Rekreacija(12, new Cas(16, 49), true),
            new Tretja.SluzbenaPot(13, new Cas(17, 43), true),
            new Tretja.SluzbenaPot(9, new Cas(17, 49), false),
            new Tretja.Rekreacija(8, new Cas(18, 18), false),
            new Tretja.SluzbenaPot(17, new Cas(18, 33), false),
            new Tretja.Rekreacija(16, new Cas(18, 37), false),
            new Tretja.Rekreacija(18, new Cas(18, 48), true),
            new Tretja.SluzbenaPot(14, new Cas(18, 52), false),
            new Tretja.Malica(14, new Cas(19, 0), true),
            new Tretja.Rekreacija(1, new Cas(19, 23), false),
            new Tretja.SluzbenaPot(4, new Cas(19, 44), false),
            new Tretja.Rekreacija(11, new Cas(19, 49), false),
            new Tretja.Malica(14, new Cas(20, 12), false),
            new Tretja.Rekreacija(2, new Cas(20, 32), false),
            new Tretja.SluzbenaPot(23, new Cas(20, 33), false),
            new Tretja.Malica(19, new Cas(20, 38), true),
            new Tretja.SluzbenaPot(4, new Cas(20, 42), true),
            new Tretja.SluzbenaPot(4, new Cas(20, 59), false),
            new Tretja.SluzbenaPot(5, new Cas(21, 10), false),
            new Tretja.Malica(19, new Cas(21, 49), false),
            new Tretja.SluzbenaPot(10, new Cas(22, 4), false),
            new Tretja.SluzbenaPot(7, new Cas(22, 6), false),
            new Tretja.Rekreacija(18, new Cas(22, 11), false),
            new Tretja.Rekreacija(6, new Cas(22, 41), false),
            new Tretja.Rekreacija(12, new Cas(22, 41), false),
            new Tretja.Rekreacija(21, new Cas(22, 42), false),
            new Tretja.SluzbenaPot(20, new Cas(22, 51), false),
            new Tretja.SluzbenaPot(13, new Cas(22, 54), false),
            new Tretja.Rekreacija(15, new Cas(23, 5), false),
            new Tretja.Rekreacija(6, new Cas(23, 9), true),
            new Tretja.Malica(3, new Cas(23, 33), false),
            new Tretja.Malica(22, new Cas(23, 36), false),
            new Tretja.Rekreacija(6, new Cas(23, 40), false),
            new Tretja.SluzbenaPot(0, new Cas(23, 43), false),
        };

        int stZaposlenih = 24;
        Tretja.Dnevnik dnevnik = new Tretja.Dnevnik(stZaposlenih, dogodki);

        for (int i = 0; i < stZaposlenih; i++) {
            System.out.printf("%d -> %d%n", i, dnevnik.kolikoRekreacije(i));
        }
        System.out.println();
    }
}
