
import java.util.*;

public class Test30 {

    public static void main(String[] args) {

        Tretja.Dogodek[] dogodki = {
            new Tretja.Rekreacija(3, new Cas(0, 0), true),
            new Tretja.SluzbenaPot(12, new Cas(0, 2), true),
            new Tretja.Rekreacija(13, new Cas(0, 12), true),
            new Tretja.Rekreacija(5, new Cas(0, 14), true),
            new Tretja.SluzbenaPot(8, new Cas(0, 18), true),
            new Tretja.SluzbenaPot(8, new Cas(0, 28), false),
            new Tretja.Rekreacija(3, new Cas(0, 52), false),
            new Tretja.Malica(0, new Cas(0, 55), true),
            new Tretja.Rekreacija(3, new Cas(1, 0), true),
            new Tretja.Rekreacija(6, new Cas(1, 5), true),
            new Tretja.Rekreacija(11, new Cas(1, 6), true),
            new Tretja.Malica(10, new Cas(1, 7), true),
            new Tretja.SluzbenaPot(7, new Cas(1, 17), true),
            new Tretja.Malica(4, new Cas(1, 22), true),
            new Tretja.Rekreacija(2, new Cas(1, 25), true),
            new Tretja.SluzbenaPot(7, new Cas(1, 39), false),
            new Tretja.Malica(7, new Cas(1, 42), true),
            new Tretja.Rekreacija(6, new Cas(1, 48), false),
            new Tretja.Rekreacija(6, new Cas(1, 49), true),
            new Tretja.Malica(8, new Cas(2, 9), true),
            new Tretja.Malica(10, new Cas(2, 14), false),
            new Tretja.Rekreacija(11, new Cas(2, 38), false),
            new Tretja.Malica(9, new Cas(2, 55), true),
            new Tretja.SluzbenaPot(12, new Cas(3, 26), false),
            new Tretja.SluzbenaPot(1, new Cas(3, 29), true),
            new Tretja.Rekreacija(11, new Cas(4, 31), true),
            new Tretja.Malica(0, new Cas(4, 34), false),
            new Tretja.Malica(12, new Cas(4, 49), true),
            new Tretja.SluzbenaPot(10, new Cas(4, 49), true),
            new Tretja.Rekreacija(6, new Cas(5, 1), false),
            new Tretja.Malica(8, new Cas(5, 9), false),
            new Tretja.SluzbenaPot(1, new Cas(6, 21), false),
            new Tretja.SluzbenaPot(6, new Cas(6, 33), true),
            new Tretja.SluzbenaPot(0, new Cas(6, 36), true),
            new Tretja.SluzbenaPot(8, new Cas(6, 43), true),
            new Tretja.SluzbenaPot(6, new Cas(7, 7), false),
            new Tretja.Malica(4, new Cas(7, 8), false),
            new Tretja.Malica(7, new Cas(7, 8), false),
            new Tretja.Rekreacija(4, new Cas(7, 15), true),
            new Tretja.SluzbenaPot(7, new Cas(7, 16), true),
            new Tretja.SluzbenaPot(1, new Cas(7, 23), true),
            new Tretja.SluzbenaPot(6, new Cas(8, 2), true),
            new Tretja.Rekreacija(4, new Cas(8, 12), false),
            new Tretja.SluzbenaPot(8, new Cas(8, 13), false),
            new Tretja.SluzbenaPot(4, new Cas(8, 30), true),
            new Tretja.SluzbenaPot(6, new Cas(8, 30), false),
            new Tretja.SluzbenaPot(6, new Cas(8, 47), true),
            new Tretja.SluzbenaPot(4, new Cas(8, 50), false),
            new Tretja.SluzbenaPot(4, new Cas(8, 56), true),
            new Tretja.Rekreacija(5, new Cas(9, 5), false),
            new Tretja.Rekreacija(5, new Cas(9, 14), true),
            new Tretja.Rekreacija(8, new Cas(9, 15), true),
            new Tretja.Rekreacija(2, new Cas(9, 36), false),
            new Tretja.Rekreacija(11, new Cas(9, 43), false),
            new Tretja.Rekreacija(5, new Cas(9, 54), false),
            new Tretja.Malica(5, new Cas(11, 38), true),
            new Tretja.Malica(2, new Cas(11, 45), true),
            new Tretja.SluzbenaPot(6, new Cas(11, 58), false),
            new Tretja.Malica(11, new Cas(11, 59), true),
            new Tretja.Malica(6, new Cas(12, 26), true),
            new Tretja.SluzbenaPot(0, new Cas(12, 50), false),
            new Tretja.Malica(11, new Cas(13, 2), false),
            new Tretja.Rekreacija(11, new Cas(13, 4), true),
            new Tretja.Rekreacija(11, new Cas(13, 5), false),
            new Tretja.Malica(5, new Cas(13, 7), false),
            new Tretja.Rekreacija(11, new Cas(13, 11), true),
            new Tretja.Rekreacija(11, new Cas(13, 14), false),
            new Tretja.SluzbenaPot(0, new Cas(13, 20), true),
            new Tretja.SluzbenaPot(5, new Cas(13, 27), true),
            new Tretja.SluzbenaPot(10, new Cas(13, 34), false),
            new Tretja.Rekreacija(10, new Cas(13, 48), true),
            new Tretja.SluzbenaPot(5, new Cas(13, 52), false),
            new Tretja.SluzbenaPot(5, new Cas(14, 2), true),
            new Tretja.SluzbenaPot(4, new Cas(14, 11), false),
            new Tretja.Rekreacija(11, new Cas(14, 44), true),
            new Tretja.Malica(6, new Cas(14, 59), false),
            new Tretja.SluzbenaPot(6, new Cas(15, 1), true),
            new Tretja.Rekreacija(10, new Cas(15, 3), false),
            new Tretja.SluzbenaPot(6, new Cas(15, 5), false),
            new Tretja.Rekreacija(11, new Cas(15, 14), false),
            new Tretja.Rekreacija(10, new Cas(15, 21), true),
            new Tretja.SluzbenaPot(5, new Cas(15, 34), false),
            new Tretja.Rekreacija(4, new Cas(15, 48), true),
            new Tretja.Rekreacija(3, new Cas(15, 51), false),
            new Tretja.SluzbenaPot(1, new Cas(16, 7), false),
            new Tretja.SluzbenaPot(11, new Cas(16, 23), true),
            new Tretja.Rekreacija(1, new Cas(16, 38), true),
            new Tretja.Rekreacija(4, new Cas(16, 47), false),
            new Tretja.SluzbenaPot(0, new Cas(16, 50), false),
            new Tretja.SluzbenaPot(4, new Cas(16, 51), true),
            new Tretja.SluzbenaPot(5, new Cas(17, 5), true),
            new Tretja.SluzbenaPot(0, new Cas(17, 10), true),
            new Tretja.SluzbenaPot(11, new Cas(17, 10), false),
            new Tretja.Malica(3, new Cas(17, 22), true),
            new Tretja.Rekreacija(13, new Cas(17, 29), false),
            new Tretja.SluzbenaPot(5, new Cas(17, 42), false),
            new Tretja.Rekreacija(6, new Cas(17, 50), true),
            new Tretja.Rekreacija(13, new Cas(17, 51), true),
            new Tretja.Malica(9, new Cas(17, 54), false),
            new Tretja.SluzbenaPot(9, new Cas(18, 3), true),
            new Tretja.SluzbenaPot(4, new Cas(18, 8), false),
            new Tretja.Rekreacija(4, new Cas(18, 9), true),
            new Tretja.Rekreacija(11, new Cas(18, 12), true),
            new Tretja.Rekreacija(5, new Cas(18, 55), true),
            new Tretja.Rekreacija(10, new Cas(19, 1), false),
            new Tretja.Rekreacija(11, new Cas(19, 2), false),
            new Tretja.Rekreacija(4, new Cas(19, 7), false),
            new Tretja.Rekreacija(4, new Cas(19, 10), true),
            new Tretja.Rekreacija(11, new Cas(19, 10), true),
            new Tretja.Malica(3, new Cas(19, 13), false),
            new Tretja.Malica(2, new Cas(19, 39), false),
            new Tretja.Rekreacija(11, new Cas(19, 49), false),
            new Tretja.SluzbenaPot(2, new Cas(20, 5), true),
            new Tretja.SluzbenaPot(3, new Cas(20, 27), true),
            new Tretja.SluzbenaPot(0, new Cas(20, 35), false),
            new Tretja.Rekreacija(5, new Cas(20, 47), false),
            new Tretja.Rekreacija(11, new Cas(21, 14), true),
            new Tretja.Rekreacija(0, new Cas(21, 43), true),
            new Tretja.SluzbenaPot(3, new Cas(21, 54), false),
            new Tretja.SluzbenaPot(7, new Cas(21, 58), false),
            new Tretja.SluzbenaPot(2, new Cas(22, 3), false),
            new Tretja.Rekreacija(1, new Cas(22, 24), false),
            new Tretja.Rekreacija(0, new Cas(22, 34), false),
            new Tretja.Rekreacija(6, new Cas(22, 34), false),
            new Tretja.SluzbenaPot(9, new Cas(22, 41), false),
            new Tretja.Rekreacija(8, new Cas(22, 43), false),
            new Tretja.Rekreacija(11, new Cas(22, 51), false),
            new Tretja.Rekreacija(0, new Cas(23, 5), true),
            new Tretja.Malica(12, new Cas(23, 31), false),
            new Tretja.Rekreacija(0, new Cas(23, 31), false),
            new Tretja.Rekreacija(13, new Cas(23, 51), false),
            new Tretja.Rekreacija(4, new Cas(23, 59), false),
        };

        int stZaposlenih = 14;
        Tretja.Dnevnik dnevnik = new Tretja.Dnevnik(stZaposlenih, dogodki);

        for (int i = 0; i < stZaposlenih; i++) {
            System.out.printf("%d -> %d%n", i, dnevnik.kolikoRekreacije(i));
        }
        System.out.println();
    }
}
