
import java.util.*;

public class Test48 {

    public static void main(String[] args) {
        List<String> la = List.of("aej", "ajn", "amx", "anp", "aou", "aqb", "aqk", "asp", "atz", "avt", "awl", "axc", "bbs", "bci", "bck", "bek", "beu", "bgn", "bhb", "bkc", "bki", "bli", "bqa", "brd", "bre", "bvj", "bwe", "ceb", "ceo", "cgg", "chx", "cia", "ckl", "cnj", "coq", "cor", "cpn", "cxd", "cxi", "czw", "dae", "dam", "ddp", "deo", "dgv", "djc", "dkg", "dng", "dns", "dom", "dop", "drs", "dsx", "duq", "dwg", "dxi", "dym", "eaa", "eaf", "ebq", "ecm", "ecy", "egx", "ehb", "ejq", "eor", "ete", "eul", "euo", "evs", "faq", "fbr", "fdr", "fey", "fgb", "fgm", "fhb", "fnt", "fsc", "fsm", "fsr", "fsw", "fty", "fyw", "gar", "gay", "gbl", "gcc", "gke", "gkm", "gkv", "gmh", "gmp", "gpw", "gqh", "gsi", "gud", "gvt", "gvu", "gwo", "gxq", "gxr", "hbb", "hfh", "hgj", "hho", "hlf", "hlg", "hnb", "hsw", "htu", "htx", "hwg", "hzf", "hzy", "iak", "ibj", "idu", "ifd", "igp", "ihb", "ihh", "ijt", "ilr", "ilx", "ins", "iqj", "iqs", "isn", "iwo", "ixh", "jag", "jaq", "jau", "jcg", "jhe", "jhn", "jkl", "jkn", "jsq", "jvs", "jwb", "kbj", "kbp", "kcw", "kcy", "kfm", "kge", "khz", "kkb", "ksv", "ktu", "lat", "lcv", "lda", "lju", "lks", "lll", "lmq", "lsx", "lts", "ltv", "lvg", "lxu", "lzk", "mdq", "mdr", "meu", "mey", "mfr", "mgz", "mhg", "mjm", "mjw", "mle", "mmv", "mnc", "mnh", "mol", "msg", "mun", "mve", "mwq", "myf", "nak", "ndp", "ngd", "nie", "njt", "nlk", "nlm", "nqv", "nut", "nwd", "odb", "odl", "ojp", "okb", "omm", "ond", "onv", "ooh", "oqq", "oqt", "org", "orr", "ose", "oth", "owl", "owo", "oyu", "pcq", "pde", "pdu", "pel", "peu", "pex", "pgc", "plc", "pli", "pls", "pns", "ppm", "pqb", "puv", "pvj", "pvl", "pvm", "pwa", "pwz", "pxs", "pzh", "qby", "qci", "qfh", "qfr", "qfu", "qij", "qlr", "qlt", "qlx", "qnb", "qnf", "qrm", "qsj", "qtr", "rbm", "rby", "rct", "rcz", "rgp", "rgu", "rjl", "rjp", "rko", "rks", "rlu", "rng", "rnn", "rvp", "rwo", "rza", "rzc", "sbm", "scv", "sdv", "sdx", "sfg", "sfj", "sgf", "siv", "sjq", "smo", "snb", "sou", "sql", "sud", "suq", "suw", "svl", "sxh", "syq", "sys", "tat", "tbn", "tbv", "tcf", "tdz", "tfe", "tfg", "tir", "tjb", "tln", "tmt", "tpg", "tsn", "tsr", "tuh", "uak", "ubz", "uhd", "uky", "uls", "uof", "uok", "uqh", "urh", "usg", "uts", "uue", "uvd", "uwf", "uxe", "uxj", "uyl", "uzg", "vbo", "vef", "vgd", "vif", "vjq", "vrw", "vtf", "vws", "vyk", "vyo", "wbg", "wdf", "wer", "wia", "wjy", "wkh", "wlf", "wlu", "wmz", "woc", "wod", "wql", "wrd", "wtp", "wtt", "wuo", "wza", "xac", "xdd", "xen", "xfd", "xgb", "xgq", "xhv", "xja", "xkq", "xlv", "xna", "xnf", "xpn", "xrt", "xum", "xux", "yfr", "yig", "yku", "ylc", "ynh", "ynl", "yns", "ypx", "yqo", "yso", "ytq", "yuj", "yuk", "yuo", "ywa", "zac", "zae", "zaf", "zbl", "zbq", "zeq", "zes", "zfk", "zfl", "zgh", "zhq", "zkp", "zop", "zpi", "ztz", "zvg", "zxj", "zxr", "zxu", "zxz");
        List<String> lb = List.of("adx", "afe", "ajb", "amc", "aqw", "aqx", "asf", "atd", "atj", "aty", "awu", "azf", "bak", "bhh", "bjl", "bqq", "brg", "brm", "bvh", "cbk", "cdx", "cfa", "ciy", "cwq", "czu", "dgl", "dpu", "drl", "drs", "dry", "dtf", "dvk", "dyd", "eab", "ecq", "egc", "ehj", "ehw", "ekj", "ekn", "elm", "emf", "eps", "epu", "erq", "esn", "euw", "evo", "fak", "fbf", "flt", "fmf", "fqt", "fsz", "fyj", "gab", "ggo", "gma", "gmj", "gmn", "gnm", "gqn", "guc", "gwc", "gxq", "hal", "hax", "hco", "hcr", "hfw", "hil", "hiy", "hla", "hmp", "hqd", "hux", "hvl", "hyd", "hze", "ibq", "igv", "ihe", "inm", "ioh", "ipi", "ird", "iyq", "iys", "jao", "jck", "jdx", "jhn", "jqb", "juh", "jvk", "jyl", "jyo", "kbf", "kbz", "kfq", "koq", "krk", "kvh", "lbs", "len", "lij", "lmn", "lpa", "lpj", "lse", "lur", "luw", "lxa", "mcb", "mct", "mde", "mid", "mke", "mkz", "mok", "mpp", "muf", "mvq", "mys", "myt", "mza", "mzt", "nag", "nbr", "ndt", "niy", "njd", "njj", "njo", "nrj", "nwh", "oex", "ogq", "oha", "ohn", "ohx", "oii", "oju", "ong", "oph", "pku", "poy", "pvn", "pwa", "qax", "qgd", "qgl", "qia", "qjj", "qnl", "qqz", "qux", "qzy", "rec", "rkz", "rmz", "roe", "ros", "rov", "rzv", "sak", "sci", "skb", "sne", "sqq", "sth", "stq", "svf", "sxg", "syh", "tbv", "tga", "thq", "tih", "tpz", "tux", "txr", "tyl", "ugh", "uiq", "ulv", "umi", "uqf", "ure", "urr", "uud", "uve", "uwu", "uxb", "uxm", "vby", "vex", "vff", "vfu", "vgv", "vhb", "vhl", "vhm", "vxm", "vzf", "wjz", "wox", "wpd", "wpi", "wpv", "wsv", "xbf", "xep", "xfe", "xhw", "xqg", "xri", "xsj", "xxc", "xyn", "yfd", "ykv", "ymy", "ypr", "yqo", "yrn", "ysi", "ytz", "yvc", "yvr", "yxv", "zbi", "zeq", "zfp", "zfq", "zgq", "zia", "zox", "zpe", "zvr");
        List<String> lc = it2list(Cetrta.zlitje(la.iterator(), lb.iterator()));
        System.out.println(lc);
    }

    private static <T> List<T> it2list(Iterator<T> it) {
        List<T> seznam = new ArrayList<>();
        while (it.hasNext()) {
            T element = it.next();
            seznam.add(element);
        }
        return seznam;
    }
}
