
import java.util.*;

public class Test30 {

    public static void main(String[] args) {
        List<String> la = List.of("aah", "aau", "abi", "adf", "ahj", "aij", "ajt", "ant", "apt", "aqm", "aum", "awp", "axv", "azf", "bba", "bcj", "bef", "bfu", "bji", "bls", "bmt", "bqn", "btn", "bwm", "bzf", "cdp", "cdy", "cez", "chc", "chn", "cil", "ckp", "clv", "cnc", "cqp", "cqt", "ctp", "cuh", "cvt", "cyg", "czc", "dae", "def", "dfp", "dhx", "djg", "dlp", "dqr", "drt", "dww", "dzd", "eaf", "ebi", "ebz", "edo", "egu", "ejy", "eko", "eln", "eno", "eow", "eqm", "esc", "etq", "eul", "eur", "evx", "eye", "eyt", "ezr", "faj", "fbj", "fdu", "fdz", "fek", "fht", "fiy", "fkl", "fkw", "fll", "fpz", "frc", "fxq", "fxx", "gab", "gcw", "gdl", "gep", "ggb", "ght", "git", "gjb", "gjz", "gkg", "gmt", "gnn", "gql", "grs", "gty", "hbj", "hgf", "hip", "hjv", "hmt", "hob", "hqw", "hrd", "hrv", "htp", "hvu", "hxp", "hyf", "hyy", "hzs", "ias", "ibj", "idc", "iel", "igw", "ija", "imm", "inj", "irx", "iss", "iuk", "ive", "ixi", "izi", "izq", "jab", "jaj", "jic", "jix", "jjv", "jkn", "jli", "jmv", "jnm", "jpj", "jqx", "jrb", "jud", "jut", "juw", "jwt", "jxs", "jzi", "kap", "kbv", "kcp", "ket", "kgv", "khk", "kid", "kkc", "kkn", "klx", "kny", "kpk", "kql", "krl", "kry", "kss", "kva", "kxo", "kzx", "lca", "lcv", "lfk", "lhr", "lkf", "llt", "lnl", "lot", "lqd", "lqs", "ltg", "luy", "lzq", "mdo", "mfq", "mfv", "mhq", "mjf", "mna", "moe", "mqy", "mra", "mrt", "msk", "mte", "mvb", "mvz", "mxh", "mzn", "mzt", "ncq", "nfr", "nfw", "ngj", "nhr", "nkh", "nlz", "nmh", "npy", "nqt", "nst", "nuc", "nvt", "nwt", "nyd", "obe", "ocs", "oet", "ogb", "ogy", "oip", "oji", "omk", "onq", "ooj", "opq", "orl", "ovh", "owr", "oxe", "oyr", "paj", "pbc", "pdu", "pfk", "pfv", "pgk", "pgr", "phx", "pjd", "pnt", "ppn", "prh", "ptb", "puw", "pyq", "qbu", "qcw", "qen", "qey", "qfj", "qia", "qlu", "qmh", "qnl", "qqa", "qtd", "qvx", "qxo", "qxy", "qzb", "rbd", "rcw", "ree", "rga", "rij", "rjf", "rjp", "rnw", "roj", "rrk", "rtl", "rvs", "rwm", "rya", "rzh", "sae", "saq", "sda", "sdo", "sge", "sij", "sji", "skp", "skx", "sna", "srj", "ssk", "sue", "swz", "syy", "szy", "tbi", "tbo", "tcm", "teh", "tgd", "the", "tjg", "tjm", "tki", "tnj", "tpj", "trb", "trk", "tvh", "txk", "tyy", "tzp", "ual", "ubr", "udd", "ufk", "uix", "ukk", "ulw", "unw", "upf", "urh", "usj", "uwr", "uxl", "uzb", "uzw", "vcr", "veh", "vev", "vik", "vjg", "vkg", "vkt", "vnx", "voy", "vqj", "vrw", "vsp", "vue", "vvz", "vwm", "wan", "wbr", "wch", "wfk", "wfw", "wgv", "whf", "wio", "wiy", "wjp", "wjr", "wmt", "woe", "wrd", "wwl", "wwv", "wyc", "wzb", "xbc", "xdt", "xgq", "xjm", "xld", "xly", "xpt", "xsj", "xvb", "xvh", "xwo", "xxa", "xyk", "yay", "ydn", "ygm", "yjg", "yjz", "ylc", "ylw", "ymk", "ynu", "ypu", "yqy", "ytq", "yyb", "yzk", "zbk", "zeg", "zfw", "zgb", "zhu", "zjh", "zmd", "zmv", "zoh", "zqu", "zrk", "zwo", "zyd", "zzt");
        List<String> lb = List.of("aaq", "abg", "acm", "agu", "ahu", "aio", "akc", "aou", "aql", "auh", "auq", "axd", "ayi", "azt", "bca", "bcq", "bfq", "biy", "bkl", "blu", "boc", "brk", "btu", "bwu", "ccj", "cdq", "ced", "cge", "chg", "cig", "ckg", "ckr", "cmu", "con", "cqr", "cth", "cua", "cuq", "cxg", "czb", "czx", "ddt", "dei", "dhd", "dic", "dkc", "dlx", "drh", "dwc", "dxy", "dzs", "eax", "ebx", "ecd", "efu", "ejb", "eke", "ekx", "enm", "enp", "epn", "ere", "eso", "etz", "euq", "eut", "ext", "eyk", "eyx", "faa", "fbb", "fck", "fdy", "fej", "feu", "fhx", "fiz", "fkt", "flb", "foi", "fqe", "frx", "fxs", "fzb", "gbs", "gda", "gdp", "gga", "gha", "ghu", "gja", "gjx", "gkc", "gkh", "gnd", "gnu", "grq", "gtg", "guk", "hbn", "hgw", "hit", "hmm", "hnn", "hpg", "hrb", "hrg", "hsq", "huv", "hvz", "hxs", "hyu", "hzi", "iap", "ibe", "ici", "iei", "ige", "igy", "ilj", "inh", "ipm", "isp", "isv", "iuy", "iwu", "ixu", "izl", "izx", "jae", "jdx", "jiq", "jjm", "jkf", "jkq", "jlx", "jnf", "jow", "jpl", "jqy", "jsp", "jur", "juu", "jux", "jxh", "jyt", "jzk", "kbf", "kce", "kef", "kgk", "kgx", "khu", "kjz", "kkl", "kle", "kmf", "kpe", "kqa", "kqm", "krm", "ksa", "kta", "kwi", "kyf", "lbn", "lcr", "ldr", "lfz", "lie", "llc", "lni", "loo", "loy", "lqk", "lrl", "lua", "lxo", "mcx", "meu", "mfr", "mfw", "mje", "mkc", "mnt", "moi", "mqz", "mrn", "msg", "msy", "mus", "mvv", "mwh", "mxu", "mzo", "nah", "nfb", "nfv", "nge", "ngq", "nin", "nlo", "nmb", "nnn", "nqf", "nrf", "nty", "nus", "nwi", "nxw", "oaw", "obk", "odl", "ofq", "ogr", "oii", "ojb", "ojj", "omp", "onx", "ooz", "oqd", "oup", "owa", "owy", "oyb", "ozn", "pao", "pbl", "pek", "pfr", "pgj", "pgl", "phl", "piz", "pko", "ppm", "ppx", "pst", "puo", "pwt", "pzv", "qbz", "qdt", "qeu", "qfa", "qhj", "qll", "qmg", "qmu", "qpk", "qrn", "quv", "qwh", "qxr", "qyl", "rbc", "rbj", "rdk", "rfq", "rhb", "rje", "rjg", "rlj", "rnz", "rqs", "rse", "ruc", "rvx", "rwq", "ryw", "rzz", "sao", "scm", "sdi", "sft", "shp", "sik", "sjy", "skv", "smw", "snd", "srq", "stb", "suv", "sxr", "szq", "tbd", "tbj", "tbs", "tcx", "tfl", "tgf", "tjd", "tjh", "tkh", "tmh", "tpc", "tqx", "trd", "tul", "tvq", "txl", "tzn", "uai", "ubg", "ucq", "ufa", "uis", "ujz", "ukt", "umx", "uok", "uqt", "urn", "utp", "uww", "uyy", "uzf", "vcd", "vea", "veq", "vfe", "vjb", "vjz", "vkh", "vkx", "vot", "vps", "vre", "vsn", "vth", "vuo", "vwj", "vxv", "wat", "wbu", "wcv", "wft", "wgu", "whd", "wil", "wip", "wjo", "wjq", "wmq", "wmu", "wqb", "wtl", "wwq", "wxl", "wyd", "xaj", "xcu", "xee", "xia", "xkz", "xlf", "xnh", "xrf", "xtu", "xvf", "xvq", "xws", "xxr", "xzc", "ycr", "ygf", "yit", "yjn", "ykx", "ylk", "ymc", "yna", "yod", "yqv", "yqz", "yug", "yyk", "yzs", "zcp", "zfv", "zfz", "zhg", "zix", "zlc", "zmk", "zoe", "zqf", "zri", "ztn", "zxw", "zyh", "zzu");
        List<String> lc = it2list(Cetrta.zlitje(la.iterator(), lb.iterator()));
        System.out.println(lc);
    }

    private static <T> List<T> it2list(Iterator<T> it) {
        List<T> seznam = new ArrayList<>();
        while (it.hasNext()) {
            T element = it.next();
            seznam.add(element);
        }
        return seznam;
    }
}
