
import java.util.*;

public class Test16 {

    public static void main(String[] args) {
        List<String> la = List.of("abf", "abi", "ace", "acg", "acj", "act", "adf", "aed", "aeq", "aga", "agt", "ahs", "ajt", "ajx", "aka", "alm", "alt", "anc", "anq", "aot", "apb", "apm", "apx", "ask", "ate", "avv", "axn", "azt", "azu", "bab", "bbz", "bcu", "bds", "bej", "bgz", "bir", "bji", "bka", "bkf", "bkj", "bkn", "bkp", "bkw", "bma", "bmc", "bmu", "bnk", "bny", "bom", "bon", "bqi", "bre", "bsg", "bui", "bun", "bve", "bvp", "bxa", "byj", "byo", "bzj", "bzo", "bzp", "car", "cba", "ccr", "ccw", "cdb", "cev", "cha", "cio", "cjh", "cjk", "cjt", "cjz", "cka", "clc", "clf", "cma", "cmg", "cmj", "cnx", "coa", "coi", "cok", "cos", "cpz", "cqg", "cry", "csf", "cta", "cva", "cvz", "cxd", "cxn", "czo", "dau", "dbb", "dbq", "dbs", "dbz", "dcz", "ddb", "dfa", "dfg", "dgh", "dhg", "dhm", "dio", "djf", "djq", "dmb", "dmn", "dnr", "dpm", "dpr", "dtt", "dtx", "duq", "dur", "dus", "dwa", "dwj", "dwo", "dwt", "dwz", "dxu", "ebx", "edm", "ees", "eft", "ego", "egq", "ehn", "emc", "emd", "eng", "enz", "eoj", "eor", "eph", "epo", "epu", "eqi", "eut", "ewa", "eyl", "ezb", "ezh", "ezi", "ezk", "ezm", "fak", "fbv", "fbw", "fbx", "fck", "feq", "fft", "ffy", "fgg", "fgr", "fin", "fjf", "fjk", "fjq", "fkq", "fli", "flq", "fmm", "fmt", "fnj", "fnu", "fpn", "fsb", "fsv", "fsy", "fuk", "fuo", "fup", "fvn", "fvr", "fvw", "fwf", "fww", "fyi", "fym", "gaq", "gbc", "gbk", "gdl", "gep", "gfq", "ggd", "ghn", "gis", "gkq", "gmr", "gmv", "grd", "grq", "gsy", "gvr", "gws", "gxm", "gyn", "gyq", "haq", "hcu", "heu", "hex", "hez", "hfb", "hfi", "hfy", "hgl", "hhz", "hif", "hiu", "hiz", "hjs", "hke", "hkw", "hlg", "hll", "hlo", "hlq", "hop", "hpk", "hqk", "hrg", "hrl", "hrm", "hsa", "hso", "hsq", "htc", "hun", "huv", "hvj", "hvn", "hwi", "hwz", "hxp", "hxv", "hyd", "hyw", "hzd", "hzi", "hzx", "iak", "iaw", "icc", "ido", "iea", "ied", "iee", "ife", "ifg", "iij", "ijy", "ikg", "ikk", "ikn", "ion", "ios", "iov", "iox", "ipc", "iqm", "iqq", "ivu", "ivx", "iwr", "ixu", "ixz", "iyb", "iyv", "izz", "jax", "jcs", "jep", "jgp", "jhs", "jju", "jli", "jlu", "jlx", "jnq", "jqj", "jql", "jqm", "jqx", "jrr", "jrt", "jsr", "jth", "jty", "jvi", "jwb", "jwd", "jwp", "jxt", "jyj", "jyu", "kcf", "kdk", "kdp", "kem", "kgl", "kgp", "kha", "khn", "kjg", "kjn", "kju", "koa", "koq", "ksr", "ksx", "kta", "kuk", "kve", "kzz", "lac", "laz", "lcp", "lcw", "ldn", "ldo", "lie", "lir", "ljh", "lji", "ljl", "ljp", "ljy", "lkf", "lmb", "lnk", "lqs", "lrd", "lrw", "lsf", "luy", "lwe", "lxm", "lyu", "lyv", "lzy", "maq", "mbl", "mbt", "mfe", "mfw", "mgb", "mhi", "mje", "mkn", "mln", "mnv", "mob", "mom", "mpg", "mpt", "mrr");
        List<String> lb = List.of("mrz", "msu", "msz", "mua", "mwh", "mww", "mwy", "myc", "mzf", "nfg", "nfy", "ngh", "ngt", "nhb", "nlf", "nml", "nnc", "nqo", "nqw", "nra", "ntg", "ntp", "nty", "nuk", "nva", "nzf", "nzz", "oab", "oax", "ocd", "oce", "ocg", "ocv", "ode", "odv", "oer", "ogi", "ojc", "ojj", "ojk", "ojo", "ojz", "oki", "ole", "oma", "oor", "oqz", "orc", "ort", "osj", "otb", "otk", "ovt", "oww", "oyk", "ozj", "paj", "pax", "pbd", "pbz", "pca", "pcb", "pcw", "pdg", "pdj", "pdw", "pfl", "pgt", "phd", "pit", "piv", "pjf", "pjw", "pkf", "plj", "pms", "pnk", "pol", "ppn", "prt", "ptd", "pti", "ptj", "puw", "pvc", "pvx", "pvz", "pwo", "pyk", "pza", "qai", "qbw", "qca", "qci", "qcx", "qds", "qez", "qfu", "qga", "qgi", "qgx", "qgz", "qia", "qiz", "qnh", "qog", "qpz", "qrb", "qrs", "qsk", "qsn", "qxd", "qyi", "qzi", "rbg", "rce", "rcg", "rcj", "rda", "rem", "req", "rey", "rfk", "rfp", "rge", "rgl", "rhl", "ria", "rij", "rio", "rjw", "rkg", "rlb", "rlq", "rnh", "rof", "row", "rpt", "rrd", "rrq", "rrt", "rsa", "rse", "rsq", "rtg", "rtj", "rtr", "rux", "rvz", "rwm", "rxr", "sah", "sap", "sbt", "seg", "sei", "sfx", "sgg", "sgi", "sgz", "shb", "shq", "sig", "siw", "sjs", "slz", "sni", "spn", "squ", "ssc", "ssh", "sth", "swq", "sxc", "sxs", "syp", "szi", "szk", "szp", "taf", "tbx", "tbz", "tca", "tcd", "tdh", "tdk", "ted", "tef", "tet", "tkb", "tkn", "tko", "tkw", "tmn", "tms", "tmy", "tnl", "tnv", "toi", "tqm", "tqs", "tqz", "trt", "tse", "tuc", "tuk", "tuu", "tvo", "txc", "tyq", "tzl", "uaj", "uay", "uce", "uch", "uff", "ufg", "ugj", "ugz", "uhg", "uim", "uiu", "ukb", "ule", "uln", "ulq", "umb", "unt", "unz", "upg", "upk", "url", "use", "utb", "utm", "utp", "uvf", "uvn", "uvy", "uwc", "uyt", "uza", "vas", "vbe", "vce", "vde", "vdg", "vfc", "vff", "vgj", "vgq", "vgu", "vhp", "vhu", "vjc", "vka", "vle", "vmi", "vmq", "vnt", "vnu", "vsf", "vte", "vtw", "vwg", "vwj", "vyo", "wah", "wbr", "wfa", "wff", "wfs", "wha", "wjd", "wjq", "wka", "wkk", "wle", "wln", "wmw", "wnu", "wqv", "wqw", "wun", "wuq", "wwf", "wws", "www", "wxb", "wxi", "wxt", "wyn", "wzq", "xbm", "xbn", "xbq", "xbs", "xbu", "xce", "xda", "xdp", "xgn", "xhm", "xjc", "xmj", "xmt", "xnj", "xnt", "xob", "xpm", "xrj", "xun", "xwa", "xwi", "xxb", "xxv", "yaj", "yan", "ybx", "ydx", "yev", "ygq", "ygv", "yhc", "yhg", "yhm", "yib", "yjx", "yku", "ylq", "ymt", "yna", "yoq", "yow", "yqc", "yrl", "yrm", "yrt", "yss", "ytm", "yur", "yux", "yvu", "ywk", "yxf", "yyp", "yzp", "yzt", "zdc", "zdl", "zdm", "zee", "zhh", "zhn", "zio", "zmh", "zmt", "znk", "zqz", "zrj", "zrm", "zrt", "zsp", "zuq", "zvi", "zwx");
        List<String> lc = it2list(Cetrta.zlitje(la.iterator(), lb.iterator()));
        System.out.println(lc);
    }

    private static <T> List<T> it2list(Iterator<T> it) {
        List<T> seznam = new ArrayList<>();
        while (it.hasNext()) {
            T element = it.next();
            seznam.add(element);
        }
        return seznam;
    }
}
