
import java.util.*;

public class Test24 {

    public static void main(String[] args) {
        List<String> la = List.of("aad", "aau", "abl", "afd", "ahr", "ajo", "ajw", "amz", "aqv", "ari", "aug", "awn", "axf", "axw", "axz", "bdv", "bfq", "bhl", "bjs", "bmw", "bni", "bqc", "bqh", "bte", "bwo", "bxw", "byx", "bzj", "ccr", "cdj", "ceh", "cie", "cjh", "ckk", "cls", "cml", "coo", "cqr", "cre", "cwd", "cyl", "dbt", "dcb", "dcd", "del", "dif", "dlh", "dms", "dpn", "dqw", "dsb", "dvb", "dwz", "dxi", "dzt", "eae", "eaq", "ebh", "ehb", "ekg", "ele", "emx", "eqs", "eui", "ewb", "eya", "ezc", "fak", "fbg", "fcf", "fcw", "ffz", "flc", "fna", "fnw", "fow", "ftb", "ftf", "fur", "fwj", "fzc", "gae", "gcc", "gdo", "geg", "gfp", "gge", "ghh", "ghp", "gly", "gmy", "gnj", "gpf", "grc", "grh", "gsd", "gtt", "gvl", "gwb", "gxv", "hak", "hbz", "hdi", "hds", "heb", "hfb", "hhs", "hjn", "hnf", "hqd", "hqp", "hry", "hsz", "hua", "hxf", "hyu", "hzv", "ibc", "ibn", "icl", "idh", "ier", "ifx", "igq", "ijb", "ilu", "imx", "inf", "iox", "irp", "itn", "iva", "ivz", "ixb", "iyq", "jds", "jgs", "jhp", "jiz", "jjs", "jks", "jli", "jmt", "jnz", "jpv", "jsj", "jvh", "jxk", "jxs", "jys", "kaq", "kbl", "kdw", "kfa", "kgn", "kig", "kkb", "kmy", "koc", "kqh", "kqv", "kui", "kwf", "kxe", "ldf", "les", "lgo", "lgt", "lic", "liv", "lkp", "lls", "lna", "lnp", "lot", "lpw", "lqm", "lsg", "lte", "lui", "lzj", "mbw", "mgj", "mia", "mig", "mji", "mkn", "mnc", "mnl", "mnv", "mqs", "mst", "mvb", "mxn", "myo", "naa", "ncf", "ngp", "ngz", "nir", "nml", "npi", "nrr", "nsd", "nsz", "nxn", "nym", "nzi", "obb", "ocz", "oes", "ofx", "ogo", "oic", "ojq", "ong", "orr", "ots", "owh", "ows", "oxk", "oym", "oyu", "pbj", "per", "pfg", "pfy", "phm", "pks", "pnr", "pqa", "prt", "pvc", "pvj", "pxg", "pzc", "qbc", "qfe", "qfz", "qhl", "qjb", "qjs", "qkc", "qkq", "qlh", "qlu", "qmp", "qoa", "qrp", "qsf", "qub", "qvz", "rda", "rei", "rgf", "rin", "rji", "rmd", "roi", "rsr", "rtf", "rto", "ruc", "rwc", "saa", "sap", "sds", "sfc", "sgg", "siq", "soc", "ssg", "svd", "sxn", "tam", "tdb", "tee", "tfb", "tgt", "tio", "tjj", "tkk", "tnx", "tpn", "tqy", "tsq", "tvv", "tzv", "ubq", "uet", "ugk", "uit", "umr", "umx", "uoa", "uok", "uri", "uru", "uss", "uvd", "uwf", "uxj", "vcg", "vdi", "vfm", "vge", "vhe", "vhk", "vjd", "vkh", "vlz", "vom", "vts", "vwi", "vxa", "vyg", "wdu", "wgq", "whn", "wng", "wod", "wph", "wqi", "wti", "wza", "wzy", "xbo", "xej", "xig", "xnw", "xpb", "xqs", "xsh", "xta", "xwr", "xxw", "yav", "ybn", "yby", "yda", "ygu", "yhg", "yhj", "yjx", "ynq", "ypl", "yqu", "yrx", "yuy", "ywh", "yxx", "yze", "yzz", "zbp", "zfh", "zfy", "zlg", "zmw", "zph", "zql", "zsa", "zvr", "zwg", "zys");
        List<String> lb = List.of("aan", "abd", "add", "ahm", "ajf", "ajt", "ajy", "anc", "ara", "asy", "avt", "awy", "axh", "axx", "bdk", "bea", "bgw", "bjg", "bla", "bne", "bnm", "bqd", "bqw", "bvb", "bxp", "byp", "byz", "cat", "ccw", "cee", "cgn", "cip", "cjy", "ckw", "cmh", "cno", "cpq", "cqz", "csc", "cwv", "czx", "dca", "dcc", "deb", "dgc", "djd", "dlp", "dmu", "dqb", "drl", "dto", "dwx", "dxb", "dxy", "dzv", "eaj", "eas", "efl", "ehe", "ekw", "eml", "epj", "ett", "evo", "ewg", "eyi", "eze", "fbd", "fbl", "fcr", "ffk", "fkw", "fmh", "fnc", "fov", "fqn", "ftc", "fun", "fux", "fyr", "fzf", "gbu", "gcj", "gee", "gfk", "gfr", "ggf", "ghm", "glh", "gmd", "gng", "gou", "gqb", "gre", "gry", "gtl", "gvc", "gvm", "gwk", "hab", "haw", "hcs", "hdm", "hdx", "hek", "hfc", "hip", "hlg", "hpx", "hqj", "hra", "hsw", "hty", "hwl", "hxq", "hza", "iaq", "ibi", "ice", "ics", "iec", "iff", "igc", "igv", "ilq", "iml", "ind", "ioe", "ipk", "isi", "itv", "ivn", "iwj", "ixq", "jcc", "jeo", "jhk", "jis", "jjl", "jko", "jlg", "jmf", "jnw", "jpk", "jqc", "jup", "jxg", "jxn", "jxz", "jyt", "kar", "kdt", "kei", "kfh", "kid", "kij", "klw", "kny", "kpk", "kqo", "kra", "kuq", "kwh", "lbs", "lea", "lev", "lgp", "lhi", "lit", "ljo", "lky", "lmn", "lnc", "lof", "lpt", "lqi", "lsf", "lsk", "lts", "lyj", "maa", "mcs", "mhz", "mie", "mih", "mju", "mlf", "mnd", "mnm", "mpy", "msc", "muc", "mvq", "mxx", "mzm", "nar", "nfq", "ngq", "nhd", "nka", "nok", "nqe", "nsa", "nsw", "nvq", "nyb", "nyo", "nzo", "obw", "oda", "ofb", "ogm", "ohw", "oiw", "onc", "onj", "osk", "ovq", "owm", "oxh", "oxs", "oys", "ozv", "pdj", "pfb", "pfx", "pgt", "piw", "pnk", "ppp", "pqx", "ptz", "pvh", "pxa", "pzb", "pzl", "qbv", "qfm", "qgx", "qhu", "qjc", "qju", "qkl", "qkw", "qlo", "qmm", "qng", "qoh", "qrz", "qsq", "qvf", "ras", "rdq", "rfp", "rgx", "riu", "rkv", "rmm", "rse", "rsw", "rtg", "rtu", "ruv", "rzt", "sab", "sck", "sel", "sga", "shb", "smq", "sqq", "ssx", "sxl", "sxw", "taz", "tdy", "tej", "tgo", "tib", "tjb", "tkg", "tlk", "toy", "tqu", "trk", "tus", "tyu", "ubj", "udt", "uex", "uin", "ukc", "ums", "uni", "uod", "upl", "urr", "usk", "utb", "uvq", "uxd", "vcf", "vdb", "veb", "vgd", "vgn", "vhi", "vie", "vjg", "vlu", "vmg", "vpj", "vuc", "vww", "vxy", "wbo", "wfi", "whl", "wih", "wnt", "won", "wpp", "wra", "wxk", "wzl", "xas", "xcg", "xfh", "xmx", "xou", "xqd", "xqy", "xss", "xuo", "xxl", "yat", "ybc", "ybp", "ycz", "yex", "yhd", "yhi", "yju", "ylf", "yoo", "ypp", "yqx", "yss", "yvw", "ywu", "yyy", "yzk", "zae", "zee", "zfi", "zjr", "zmn", "zop", "zqd", "zrp", "zsq", "zwa", "zxn", "zzg");
        List<String> lc = it2list(Cetrta.zlitje(la.iterator(), lb.iterator()));
        System.out.println(lc);
    }

    private static <T> List<T> it2list(Iterator<T> it) {
        List<T> seznam = new ArrayList<>();
        while (it.hasNext()) {
            T element = it.next();
            seznam.add(element);
        }
        return seznam;
    }
}
